# site settings
title: Girl Talk
subtitle: by Rute Correia
email: youremailaddress@gmail.com
description: An analysis of songs by female artists with natural language processing
url: # the base hostname & protocol for your site
author:
street_address:
city:
zip_code: 
country: Portugal
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/aariops
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/arutecorreia
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ruteradio
# build settings
markdown: kramdown

sass:
  style: compressed
